name: CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build_embedded:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: ${{ runner.os }}-bazel

      - name: Test
        run: |
          bazelisk test //...

      - name: Build
        run: |

          bazelisk build  --platforms=@bazel_embedded//platforms:cortex_m0 //toolchains/... //third_party_libs/... 
          bazelisk build  --platforms=@bazel_embedded//platforms:cortex_m3 //toolchains/... //third_party_libs/... 
          bazelisk build  --platforms=@bazel_embedded//platforms:cortex_m4 //toolchains/... //third_party_libs/... 
          bazelisk build  --platforms=@bazel_embedded//platforms:cortex_m4_fpu //toolchains/... //third_party_libs/... 
          bazelisk build  --platforms=@bazel_embedded//platforms:cortex_m7 //toolchains/... //third_party_libs/... 
          bazelisk build  --platforms=@bazel_embedded//platforms:cortex_m7_fpu //toolchains/... //third_party_libs/...

          bazelisk build  --platforms=@bazel_embedded//platforms:stm32f2xx //toolchains/... //third_party_libs/...
          bazelisk build  --platforms=@bazel_embedded//platforms:stm32f3xx //toolchains/... //third_party_libs/...
          bazelisk build  --platforms=@bazel_embedded//platforms:stm32f4xx //toolchains/... //third_party_libs/...
          bazelisk build  --platforms=@bazel_embedded//platforms:stm32g4xx //toolchains/... //third_party_libs/...
          bazelisk build  --platforms=@bazel_embedded//platforms:stm32h7xx //toolchains/... //third_party_libs/...

  build_host:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: ${{ runner.os }}-bazel

      - name: Test
        run: |
          bazelisk test //...

      - name: Build
        run: |
          bazelisk build  --platforms=@local_config_platform//:host //...

